### ISSUE TITLE
FaceServiceHelper.ListPersonGroupAsync(WorkspaceKey) return issue

### ISSUE THREAD

**Issue by rrvenki** [microsoft/Cognitive-Samples-IntelligentKiosk#12]
Hi,
In PersonGroupsPage.Xaml.cs, at line number 58, as below
IEnumerable<PersonGroup> personGroups = await FaceServiceHelper.ListPersonGroupsAsync(SettingsHelper.Instance.WorkspaceKey);

in debug mode, the ListPersonGroupsAsync() gets the PersonGroup array as expected.  But once returned from the function, on assigning to "IEnumerable<PersonGroup> personGroups", VS2017 says "ResultView" has to be enumerated to view results.  On enumeration it gives "Enumeration yielded no results".

This is a show stopper as without getting the "group" we are not able to work further.

**Comment by CarlosP-MS** [comment]
I don't think that is a problem with the APIs since you say it works fine during runtime. Sounds like it could be a debugging related bug in VS2017. As a workaround to confirm the theory you could try converting the results of the ListPersonGroupsAsync call to an array in your code and using that array when inspecting in Visual Studio.
