### ISSUE TITLE
Copy/Paste Not Working

### ISSUE THREAD

**Issue by godlikesme-zz** [microsoft/Cognitive-Samples-IntelligentKiosk#13]
I am trying to copy/paste the API keys and can't paste them into the app's textboxes. I don't get a context menu when attempting to use a mouse and ctrl-v doesn't work either. I should note that this issue only seems to affect the app when running it on a HoloLens device.

Apparently I'm not the only one having issues with [this](https://forums.hololens.com/discussion/1890/how-do-you-copy-paste-text-while-browsing).

**Comment by CarlosP-MS** [comment]
That is unfortunate. I am not familiar with the level of text input support in HoloLens to help explain what is going on, but if you want to get unblocked, you could consider hardcoding your various API keys in the SettingsHelper class as a workaround. For example, instead of initializing with an empty string [here](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Kiosk/SettingsHelper.cs#L233) you could use your key as a default value instead.
