### ISSUE TITLE
Not as many demos as the version available on windows store

### ISSUE THREAD

**Issue by chazwoza** [microsoft/Cognitive-Samples-IntelligentKiosk#18]
Hello,

When I run and compile this code, I only get 10 different demos. The version of intelligent kiosk available on Windows Store has 21 different samples.

Can we please get the code for the other 11?

**Comment by CarlosP-MS** [comment]
The difference comes from a couple of reasons. Some of those demos use services that are not yet publicly available, others are combined and replaced with a more generic version (by design so they don't add unnecessary noise and focus on the key common aspects, such as Automatic Photo Capture). 

With that said, there is currently a gap and some demos that should be here are not yet. Those will eventually come. Is there a particular demo you had in mind? That could help with the priority order in case it is a demo that can come over.

**Comment by chazwoza** [comment]
My favourite is the vision API explorer, so that would be my top request :)

**Comment by CarlosP-MS** [comment]
Thanks for the input. Yes, that one is in the list of demos to be added in the future.

**Comment by CarlosP-MS** [comment]
I just added the Vision API Explorer demo.
