### ISSUE TITLE
Putting Realtime Crowd Insights Example in Background or minimizing and then reactivating causes error.

### ISSUE THREAD

**Issue by mscherotter** [microsoft/Cognitive-Samples-IntelligentKiosk#32]
1. Start Realtime Crowd Insights Sample
2. Open another app in the foreground or minimize the Intelligent Kiosk app
3. Re-activeate the Intelligent Kiosk App
4. Error message "Error capturing photo" is shown.

**Comment by CarlosP-MS** [comment]
When an app is running in full screen mode (such as when the Realtime Crowd Insights demo is running), Windows will shut down the camera when the app goes to the background. When you switch back to the kiosk app there is an event handler that detects window reactivation, at which point it restarts the camera. 

The error that you are seeing is because during a short period of time after reactivation the camera is not quite ready yet to take photos (which the demo tries to do at 1fps). You can silence the errors by setting the camera control to stop raising camera capture errors. For that, just set ShowDialogOnApiErrors property to False in the CameraControl instance used in the Realtime Crowd Insights demo.
