### ISSUE TITLE
Multiple Endpoints for Text Analytics in Container

### ISSUE THREAD

**Issue by kevintupper** [microsoft/Cognitive-Samples-IntelligentKiosk#64]
Cognitive Services are now available via containers.  Containerized text analytics is split out into 3 different containers.  The Kiosk settings page only provides for one text analytics endpoint.  If we are to effectively demo containerized services we will need an endpoint for each of the kinds of containers.

**Comment by CarlosP-MS** [comment]
Thanks for the feedback. We are aware of the limitations of Text Analytics and Computer Vision in the kiosk, and will update this issue if we end up adding support for providing multiple container endpoints. 

Please notice the Face container works well since it offers the full API support in a single container. I would recommend using that one as an effective way of showing containers with the kiosk app.
